---
version: '3.7'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "${WORDPRESS_PORT}:80"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: db
    volumes:
      - html_dir:/var/www/html
      - ./resist:/var/www/html/wp-content/themes/resist
      - ./docker/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/script:/script/

  db:
    image: mariadb:10.7
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE:  "${WORDPRESS_DB_NAME}"
      MYSQL_USER: "${WORDPRESS_DB_USER}"
      MYSQL_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
    volumes:
      - mysql_dir:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_USER: "${WORDPRESS_DB_USER}"
      PMA_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      PMA_ARBITRARY: 1

volumes:
  html_dir:
  mysql_dir:
