#!/bin/sh

set -e

SCRIPTDIR="$(dirname $0)"

cd "$SCRIPTDIR/.."

script/update

rsync --verbose --compress --update --delete --recursive --group --times --progress --omit-dir-times --no-perms "resist" "itsaboutpeepl.com:~/public_html/wp-content/themes"
